// HT66F3195.h
//	This file contains the definition of registers for
//		Holtek HT66F3195 microcontroller.
//	Generated by HTFileParse.dll.
//	[VERSION] 1.7, 4
// Do not modify manually.

#ifndef _HT66F3195_H_
#define _HT66F3195_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char __cz : 1;
	unsigned char __sc : 1;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char __lrf : 1;
	unsigned char __lvrf : 1;
	unsigned char __rstf : 1;
	unsigned char : 4;
} __rstfc_bits;

typedef union {
	__rstfc_bits bits;
	__sfr_byte byte;
} __rstfc_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char : 4;
} __integ_bits;

typedef union {
	__integ_bits bits;
	__sfr_byte byte;
} __integ_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __int0e : 1;
	unsigned char __cpe : 1;
	unsigned char __mf0e : 1;
	unsigned char __int0f : 1;
	unsigned char __cpf : 1;
	unsigned char __mf0f : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __mf1e : 1;
	unsigned char __mf2e : 1;
	unsigned char __ade : 1;
	unsigned char __tb0e : 1;
	unsigned char __mf1f : 1;
	unsigned char __mf2f : 1;
	unsigned char __adf : 1;
	unsigned char __tb0f : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __tb1e : 1;
	unsigned char __int1e : 1;
	unsigned char __sime : 1;
	unsigned char __uarte : 1;
	unsigned char __tb1f : 1;
	unsigned char __int1f : 1;
	unsigned char __simf : 1;
	unsigned char __uartf : 1;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __fsiden : 1;
	unsigned char __fhiden : 1;
	unsigned char __fss : 1;
	unsigned char __fhs : 1;
	unsigned char : 1;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __scc_bits;

typedef union {
	__scc_bits bits;
	__sfr_byte byte;
} __scc_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char : 4;
	unsigned char __tb0on : 1;
} __tb0c_bits;

typedef union {
	__tb0c_bits bits;
	__sfr_byte byte;
} __tb0c_type;

typedef struct {
	unsigned char __hircen : 1;
	unsigned char __hircf : 1;
	unsigned char __hirc0 : 1;
	unsigned char __hirc1 : 1;
	unsigned char : 4;
} __hircc_bits;

typedef union {
	__hircc_bits bits;
	__sfr_byte byte;
} __hircc_type;

typedef struct {
	unsigned char __lvs0 : 1;
	unsigned char __lvs1 : 1;
	unsigned char __lvs2 : 1;
	unsigned char __lvs3 : 1;
	unsigned char __lvs4 : 1;
	unsigned char __lvs5 : 1;
	unsigned char __lvs6 : 1;
	unsigned char __lvs7 : 1;
} __lvrc_bits;

typedef union {
	__lvrc_bits bits;
	__sfr_byte byte;
} __lvrc_type;

typedef struct {
	unsigned char __eea0 : 1;
	unsigned char __eea1 : 1;
	unsigned char __eea2 : 1;
	unsigned char __eea3 : 1;
	unsigned char __eea4 : 1;
	unsigned char __eea5 : 1;
	unsigned char __eea6 : 1;
	unsigned char : 1;
} __eea_bits;

typedef union {
	__eea_bits bits;
	__sfr_byte byte;
} __eea_type;

typedef struct {
	unsigned char __sacs0 : 1;
	unsigned char __sacs1 : 1;
	unsigned char __sacs2 : 1;
	unsigned char __sacs3 : 1;
	unsigned char __adrfs : 1;
	unsigned char __adcen : 1;
	unsigned char __adbz : 1;
	unsigned char __start : 1;
} __sadc0_bits;

typedef union {
	__sadc0_bits bits;
	__sfr_byte byte;
} __sadc0_type;

typedef struct {
	unsigned char __sacks0 : 1;
	unsigned char __sacks1 : 1;
	unsigned char __sacks2 : 1;
	unsigned char : 1;
	unsigned char __sains0 : 1;
	unsigned char __sains1 : 1;
	unsigned char __sains2 : 1;
	unsigned char __sains3 : 1;
} __sadc1_bits;

typedef union {
	__sadc1_bits bits;
	__sfr_byte byte;
} __sadc1_type;

typedef struct {
	unsigned char __pgags0 : 1;
	unsigned char __pgags1 : 1;
	unsigned char __savrs0 : 1;
	unsigned char __savrs1 : 1;
	unsigned char __pgais : 1;
	unsigned char : 2;
	unsigned char __adpgaen : 1;
} __sadc2_bits;

typedef union {
	__sadc2_bits bits;
	__sfr_byte byte;
} __sadc2_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char __pb3 : 1;
	unsigned char __pb4 : 1;
	unsigned char __pb5 : 1;
	unsigned char __pb6 : 1;
	unsigned char : 1;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char __pbc3 : 1;
	unsigned char __pbc4 : 1;
	unsigned char __pbc5 : 1;
	unsigned char __pbc6 : 1;
	unsigned char : 1;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char __pbpu3 : 1;
	unsigned char __pbpu4 : 1;
	unsigned char __pbpu5 : 1;
	unsigned char __pbpu6 : 1;
	unsigned char : 1;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char : 3;
	unsigned char __cton : 1;
	unsigned char __ctck0 : 1;
	unsigned char __ctck1 : 1;
	unsigned char __ctck2 : 1;
	unsigned char __ctpau : 1;
} __ctmc0_bits;

typedef union {
	__ctmc0_bits bits;
	__sfr_byte byte;
} __ctmc0_type;

typedef struct {
	unsigned char __ctcclr : 1;
	unsigned char __ctdpx : 1;
	unsigned char __ctpol : 1;
	unsigned char __ctoc : 1;
	unsigned char __ctio0 : 1;
	unsigned char __ctio1 : 1;
	unsigned char __ctm0 : 1;
	unsigned char __ctm1 : 1;
} __ctmc1_bits;

typedef union {
	__ctmc1_bits bits;
	__sfr_byte byte;
} __ctmc1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __ston : 1;
	unsigned char __stck0 : 1;
	unsigned char __stck1 : 1;
	unsigned char __stck2 : 1;
	unsigned char __stpau : 1;
} __stmc0_bits;

typedef union {
	__stmc0_bits bits;
	__sfr_byte byte;
} __stmc0_type;

typedef struct {
	unsigned char __stcclr : 1;
	unsigned char __stdpx : 1;
	unsigned char __stpol : 1;
	unsigned char __stoc : 1;
	unsigned char __stio0 : 1;
	unsigned char __stio1 : 1;
	unsigned char __stm0 : 1;
	unsigned char __stm1 : 1;
} __stmc1_bits;

typedef union {
	__stmc1_bits bits;
	__sfr_byte byte;
} __stmc1_type;

typedef struct {
	unsigned char __strp0 : 1;
	unsigned char __strp1 : 1;
	unsigned char __strp2 : 1;
	unsigned char __strp3 : 1;
	unsigned char __strp4 : 1;
	unsigned char __strp5 : 1;
	unsigned char __strp6 : 1;
	unsigned char __strp7 : 1;
} __stmrp_bits;

typedef union {
	__stmrp_bits bits;
	__sfr_byte byte;
} __stmrp_type;

typedef struct {
	unsigned char __hxten : 1;
	unsigned char __hxtf : 1;
	unsigned char __hxtm : 1;
	unsigned char : 5;
} __hxtc_bits;

typedef union {
	__hxtc_bits bits;
	__sfr_byte byte;
} __hxtc_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pton : 1;
	unsigned char __ptck0 : 1;
	unsigned char __ptck1 : 1;
	unsigned char __ptck2 : 1;
	unsigned char __ptpau : 1;
} __ptmc0_bits;

typedef union {
	__ptmc0_bits bits;
	__sfr_byte byte;
} __ptmc0_type;

typedef struct {
	unsigned char __ptcclr : 1;
	unsigned char __ptcapts : 1;
	unsigned char __ptpol : 1;
	unsigned char __ptoc : 1;
	unsigned char __ptio0 : 1;
	unsigned char __ptio1 : 1;
	unsigned char __ptm0 : 1;
	unsigned char __ptm1 : 1;
} __ptmc1_bits;

typedef union {
	__ptmc1_bits bits;
	__sfr_byte byte;
} __ptmc1_type;

typedef struct {
	unsigned char __ptrp0 : 1;
	unsigned char __ptrp1 : 1;
	unsigned char __ptrp2 : 1;
	unsigned char __ptrp3 : 1;
	unsigned char __ptrp4 : 1;
	unsigned char __ptrp5 : 1;
	unsigned char __ptrp6 : 1;
	unsigned char __ptrp7 : 1;
} __ptmrpl_bits;

typedef union {
	__ptmrpl_bits bits;
	__sfr_byte byte;
} __ptmrpl_type;

typedef struct {
	unsigned char __ptrp8 : 1;
	unsigned char __ptrp9 : 1;
	unsigned char : 6;
} __ptmrph_bits;

typedef union {
	__ptmrph_bits bits;
	__sfr_byte byte;
} __ptmrph_type;

typedef struct {
	unsigned char __cmphyen : 1;
	unsigned char : 3;
	unsigned char __cmpo : 1;
	unsigned char __cmppol : 1;
	unsigned char __cmpen : 1;
	unsigned char : 1;
} __cmpc_bits;

typedef union {
	__cmpc_bits bits;
	__sfr_byte byte;
} __cmpc_type;

typedef struct {
	unsigned char __pc0 : 1;
	unsigned char __pc1 : 1;
	unsigned char __pc2 : 1;
	unsigned char __pc3 : 1;
	unsigned char __pc4 : 1;
	unsigned char __pc5 : 1;
	unsigned char __pc6 : 1;
	unsigned char : 1;
} __pc_bits;

typedef union {
	__pc_bits bits;
	__sfr_byte byte;
} __pc_type;

typedef struct {
	unsigned char __pcc0 : 1;
	unsigned char __pcc1 : 1;
	unsigned char __pcc2 : 1;
	unsigned char __pcc3 : 1;
	unsigned char __pcc4 : 1;
	unsigned char __pcc5 : 1;
	unsigned char __pcc6 : 1;
	unsigned char : 1;
} __pcc_bits;

typedef union {
	__pcc_bits bits;
	__sfr_byte byte;
} __pcc_type;

typedef struct {
	unsigned char __pcpu0 : 1;
	unsigned char __pcpu1 : 1;
	unsigned char __pcpu2 : 1;
	unsigned char __pcpu3 : 1;
	unsigned char __pcpu4 : 1;
	unsigned char __pcpu5 : 1;
	unsigned char __pcpu6 : 1;
	unsigned char : 1;
} __pcpu_bits;

typedef union {
	__pcpu_bits bits;
	__sfr_byte byte;
} __pcpu_type;

typedef struct {
	unsigned char __lxten : 1;
	unsigned char __lxtf : 1;
	unsigned char __lxtsp : 1;
	unsigned char : 5;
} __lxtc_bits;

typedef union {
	__lxtc_bits bits;
	__sfr_byte byte;
} __lxtc_type;

typedef struct {
	unsigned char __simicf : 1;
	unsigned char __simen : 1;
	unsigned char __simdeb0 : 1;
	unsigned char __simdeb1 : 1;
	unsigned char : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __iamwu : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char : 1;
	unsigned char __sima0 : 1;
	unsigned char __sima1 : 1;
	unsigned char __sima2 : 1;
	unsigned char __sima3 : 1;
	unsigned char __sima4 : 1;
	unsigned char __sima5 : 1;
	unsigned char __sima6 : 1;
} __sima_bits;

typedef union {
	__sima_bits bits;
	__sfr_byte byte;
} __sima_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char __simtos0 : 1;
	unsigned char __simtos1 : 1;
	unsigned char __simtos2 : 1;
	unsigned char __simtos3 : 1;
	unsigned char __simtos4 : 1;
	unsigned char __simtos5 : 1;
	unsigned char __simtof : 1;
	unsigned char __simtoen : 1;
} __simtoc_bits;

typedef union {
	__simtoc_bits bits;
	__sfr_byte byte;
} __simtoc_type;

typedef struct {
	unsigned char __vbgren : 1;
	unsigned char : 7;
} __vbgrc_bits;

typedef union {
	__vbgrc_bits bits;
	__sfr_byte byte;
} __vbgrc_type;

typedef struct {
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tb12 : 1;
	unsigned char : 4;
	unsigned char __tb1on : 1;
} __tb1c_bits;

typedef union {
	__tb1c_bits bits;
	__sfr_byte byte;
} __tb1c_type;

typedef struct {
	unsigned char __stmpe : 1;
	unsigned char __stmae : 1;
	unsigned char : 2;
	unsigned char __stmpf : 1;
	unsigned char __stmaf : 1;
	unsigned char : 2;
} __mfi0_bits;

typedef union {
	__mfi0_bits bits;
	__sfr_byte byte;
} __mfi0_type;

typedef struct {
	unsigned char __ptmpe : 1;
	unsigned char __ptmae : 1;
	unsigned char __ctmpe : 1;
	unsigned char __ctmae : 1;
	unsigned char __ptmpf : 1;
	unsigned char __ptmaf : 1;
	unsigned char __ctmpf : 1;
	unsigned char __ctmaf : 1;
} __mfi1_bits;

typedef union {
	__mfi1_bits bits;
	__sfr_byte byte;
} __mfi1_type;

typedef struct {
	unsigned char __lve : 1;
	unsigned char __dee : 1;
	unsigned char : 2;
	unsigned char __lvf : 1;
	unsigned char __def : 1;
	unsigned char : 2;
} __mfi2_bits;

typedef union {
	__mfi2_bits bits;
	__sfr_byte byte;
} __mfi2_type;

typedef struct {
	unsigned char __sledc00 : 1;
	unsigned char __sledc01 : 1;
	unsigned char __sledc02 : 1;
	unsigned char __sledc03 : 1;
	unsigned char __sledc04 : 1;
	unsigned char __sledc05 : 1;
	unsigned char __sledc06 : 1;
	unsigned char __sledc07 : 1;
} __sledc0_bits;

typedef union {
	__sledc0_bits bits;
	__sfr_byte byte;
} __sledc0_type;

typedef struct {
	unsigned char __sledc10 : 1;
	unsigned char __sledc11 : 1;
	unsigned char __sledc12 : 1;
	unsigned char __sledc13 : 1;
	unsigned char __sledc14 : 1;
	unsigned char __sledc15 : 1;
	unsigned char : 2;
} __sledc1_bits;

typedef union {
	__sledc1_bits bits;
	__sfr_byte byte;
} __sledc1_type;

typedef struct {
	unsigned char __rxps : 1;
	unsigned char __scsbps : 1;
	unsigned char __sck_sclps : 1;
	unsigned char __sdi_sdaps : 1;
	unsigned char __int0ps : 1;
	unsigned char __int1ps : 1;
	unsigned char : 2;
} __ifs_bits;

typedef union {
	__ifs_bits bits;
	__sfr_byte byte;
} __ifs_type;

typedef struct {
	unsigned char __pd0 : 1;
	unsigned char __pd1 : 1;
	unsigned char __pd2 : 1;
	unsigned char __pd3 : 1;
	unsigned char : 4;
} __pd_bits;

typedef union {
	__pd_bits bits;
	__sfr_byte byte;
} __pd_type;

typedef struct {
	unsigned char __pdc0 : 1;
	unsigned char __pdc1 : 1;
	unsigned char __pdc2 : 1;
	unsigned char __pdc3 : 1;
	unsigned char : 4;
} __pdc_bits;

typedef union {
	__pdc_bits bits;
	__sfr_byte byte;
} __pdc_type;

typedef struct {
	unsigned char __pdpu0 : 1;
	unsigned char __pdpu1 : 1;
	unsigned char __pdpu2 : 1;
	unsigned char __pdpu3 : 1;
	unsigned char : 4;
} __pdpu_bits;

typedef union {
	__pdpu_bits bits;
	__sfr_byte byte;
} __pdpu_type;

typedef struct {
	unsigned char __txif : 1;
	unsigned char __tidle : 1;
	unsigned char __rxif : 1;
	unsigned char __ridle : 1;
	unsigned char __oerr : 1;
	unsigned char __ferr : 1;
	unsigned char __nf : 1;
	unsigned char __perr : 1;
} __usr_bits;

typedef union {
	__usr_bits bits;
	__sfr_byte byte;
} __usr_type;

typedef struct {
	unsigned char __tx8 : 1;
	unsigned char __rx8 : 1;
	unsigned char __txbrk : 1;
	unsigned char __stops : 1;
	unsigned char __prt : 1;
	unsigned char __pren : 1;
	unsigned char __bno : 1;
	unsigned char __uarten : 1;
} __ucr1_bits;

typedef union {
	__ucr1_bits bits;
	__sfr_byte byte;
} __ucr1_type;

typedef struct {
	unsigned char __teie : 1;
	unsigned char __tiie : 1;
	unsigned char __rie : 1;
	unsigned char __wake : 1;
	unsigned char __adden : 1;
	unsigned char __brgh : 1;
	unsigned char __rxen : 1;
	unsigned char __txen : 1;
} __ucr2_bits;

typedef union {
	__ucr2_bits bits;
	__sfr_byte byte;
} __ucr2_type;

typedef struct {
	unsigned char __brg0 : 1;
	unsigned char __brg1 : 1;
	unsigned char __brg2 : 1;
	unsigned char __brg3 : 1;
	unsigned char __brg4 : 1;
	unsigned char __brg5 : 1;
	unsigned char __brg6 : 1;
	unsigned char __brg7 : 1;
} __brg_bits;

typedef union {
	__brg_bits bits;
	__sfr_byte byte;
} __brg_type;

typedef struct {
	unsigned char __txrx0 : 1;
	unsigned char __txrx1 : 1;
	unsigned char __txrx2 : 1;
	unsigned char __txrx3 : 1;
	unsigned char __txrx4 : 1;
	unsigned char __txrx5 : 1;
	unsigned char __txrx6 : 1;
	unsigned char __txrx7 : 1;
} __txr_rxr_bits;

typedef union {
	__txr_rxr_bits bits;
	__sfr_byte byte;
} __txr_rxr_type;

typedef struct {
	unsigned char __lvpu : 1;
	unsigned char : 7;
} __lvpuc_bits;

typedef union {
	__lvpuc_bits bits;
	__sfr_byte byte;
} __lvpuc_type;

typedef struct {
	unsigned char __pas00 : 1;
	unsigned char __pas01 : 1;
	unsigned char __pas02 : 1;
	unsigned char __pas03 : 1;
	unsigned char __pas04 : 1;
	unsigned char __pas05 : 1;
	unsigned char __pas06 : 1;
	unsigned char __pas07 : 1;
} __pas0_bits;

typedef union {
	__pas0_bits bits;
	__sfr_byte byte;
} __pas0_type;

typedef struct {
	unsigned char __pas10 : 1;
	unsigned char __pas11 : 1;
	unsigned char __pas12 : 1;
	unsigned char __pas13 : 1;
	unsigned char __pas14 : 1;
	unsigned char __pas15 : 1;
	unsigned char __pas16 : 1;
	unsigned char __pas17 : 1;
} __pas1_bits;

typedef union {
	__pas1_bits bits;
	__sfr_byte byte;
} __pas1_type;

typedef struct {
	unsigned char __pbs00 : 1;
	unsigned char __pbs01 : 1;
	unsigned char __pbs02 : 1;
	unsigned char __pbs03 : 1;
	unsigned char __pbs04 : 1;
	unsigned char __pbs05 : 1;
	unsigned char __pbs06 : 1;
	unsigned char __pbs07 : 1;
} __pbs0_bits;

typedef union {
	__pbs0_bits bits;
	__sfr_byte byte;
} __pbs0_type;

typedef struct {
	unsigned char __pbs10 : 1;
	unsigned char __pbs11 : 1;
	unsigned char __pbs12 : 1;
	unsigned char __pbs13 : 1;
	unsigned char __pbs14 : 1;
	unsigned char __pbs15 : 1;
	unsigned char : 2;
} __pbs1_bits;

typedef union {
	__pbs1_bits bits;
	__sfr_byte byte;
} __pbs1_type;

typedef struct {
	unsigned char __pcs00 : 1;
	unsigned char __pcs01 : 1;
	unsigned char __pcs02 : 1;
	unsigned char __pcs03 : 1;
	unsigned char __pcs04 : 1;
	unsigned char __pcs05 : 1;
	unsigned char __pcs06 : 1;
	unsigned char __pcs07 : 1;
} __pcs0_bits;

typedef union {
	__pcs0_bits bits;
	__sfr_byte byte;
} __pcs0_type;

typedef struct {
	unsigned char __pcs10 : 1;
	unsigned char __pcs11 : 1;
	unsigned char __pcs12 : 1;
	unsigned char __pcs13 : 1;
	unsigned char __pcs14 : 1;
	unsigned char __pcs15 : 1;
	unsigned char : 2;
} __pcs1_bits;

typedef union {
	__pcs1_bits bits;
	__sfr_byte byte;
} __pcs1_type;

typedef struct {
	unsigned char __pds00 : 1;
	unsigned char __pds01 : 1;
	unsigned char __pds02 : 1;
	unsigned char __pds03 : 1;
	unsigned char __pds04 : 1;
	unsigned char __pds05 : 1;
	unsigned char __pds06 : 1;
	unsigned char __pds07 : 1;
} __pds0_bits;

typedef union {
	__pds0_bits bits;
	__sfr_byte byte;
} __pds0_type;

typedef struct {
	unsigned char : 4;
	unsigned char __lcden : 1;
	unsigned char __isel0 : 1;
	unsigned char __isel1 : 1;
	unsigned char __frame : 1;
} __slcdc0_bits;

typedef union {
	__slcdc0_bits bits;
	__sfr_byte byte;
} __slcdc0_type;

typedef struct {
	unsigned char __comsegs0 : 1;
	unsigned char __comsegs1 : 1;
	unsigned char __comsegs2 : 1;
	unsigned char __comsegs3 : 1;
	unsigned char __comsegs4 : 1;
	unsigned char __comsegs5 : 1;
	unsigned char __comsegs6 : 1;
	unsigned char __comsegs7 : 1;
} __slcds0_bits;

typedef union {
	__slcds0_bits bits;
	__sfr_byte byte;
} __slcds0_type;

typedef struct {
	unsigned char __comsegs8 : 1;
	unsigned char __comsegs9 : 1;
	unsigned char __comsegs10 : 1;
	unsigned char __comsegs11 : 1;
	unsigned char __comsegs12 : 1;
	unsigned char __comsegs13 : 1;
	unsigned char __comsegs14 : 1;
	unsigned char __comsegs15 : 1;
} __slcds1_bits;

typedef union {
	__slcds1_bits bits;
	__sfr_byte byte;
} __slcds1_type;

typedef struct {
	unsigned char __comsegs16 : 1;
	unsigned char __comsegs17 : 1;
	unsigned char __comsegs18 : 1;
	unsigned char __comsegs19 : 1;
	unsigned char __comsegs20 : 1;
	unsigned char __comsegs21 : 1;
	unsigned char : 2;
} __slcds2_bits;

typedef union {
	__slcds2_bits bits;
	__sfr_byte byte;
} __slcds2_type;

typedef struct {
	unsigned char __clksel00 : 1;
	unsigned char __clksel01 : 1;
	unsigned char : 6;
} __psc0r_bits;

typedef union {
	__psc0r_bits bits;
	__sfr_byte byte;
} __psc0r_type;

typedef struct {
	unsigned char __clksel10 : 1;
	unsigned char __clksel11 : 1;
	unsigned char : 6;
} __psc1r_bits;

typedef union {
	__psc1r_bits bits;
	__sfr_byte byte;
} __psc1r_type;

typedef struct {
	unsigned char __rstc0 : 1;
	unsigned char __rstc1 : 1;
	unsigned char __rstc2 : 1;
	unsigned char __rstc3 : 1;
	unsigned char __rstc4 : 1;
	unsigned char __rstc5 : 1;
	unsigned char __rstc6 : 1;
	unsigned char __rstc7 : 1;
} __rstc_bits;

typedef union {
	__rstc_bits bits;
	__sfr_byte byte;
} __rstc_type;

typedef struct {
	unsigned char __frd : 1;
	unsigned char __frden : 1;
	unsigned char __fwt : 1;
	unsigned char __fwpen : 1;
	unsigned char __fmod0 : 1;
	unsigned char __fmod1 : 1;
	unsigned char __fmod2 : 1;
	unsigned char __cfwen : 1;
} __fc0_bits;

typedef union {
	__fc0_bits bits;
	__sfr_byte byte;
} __fc0_type;

typedef struct {
	unsigned char __clwb : 1;
	unsigned char __fwerts : 1;
	unsigned char : 6;
} __fc2_bits;

typedef union {
	__fc2_bits bits;
	__sfr_byte byte;
} __fc2_type;

typedef struct {
	unsigned char __fa0 : 1;
	unsigned char __fa1 : 1;
	unsigned char __fa2 : 1;
	unsigned char __fa3 : 1;
	unsigned char __fa4 : 1;
	unsigned char __fa5 : 1;
	unsigned char __fa6 : 1;
	unsigned char __fa7 : 1;
} __farl_bits;

typedef union {
	__farl_bits bits;
	__sfr_byte byte;
} __farl_type;

typedef struct {
	unsigned char __fa8 : 1;
	unsigned char __fa9 : 1;
	unsigned char __fa10 : 1;
	unsigned char __fa11 : 1;
	unsigned char __fa12 : 1;
	unsigned char : 3;
} __farh_bits;

typedef union {
	__farh_bits bits;
	__sfr_byte byte;
} __farh_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char __mode : 1;
	unsigned char __er : 1;
	unsigned char __eren : 1;
	unsigned char __ewerts : 1;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;


DEFINE_SFR(__sfr_byte, __mp0, 0x01);
DEFINE_SFR(__sfr_byte, __mp1l, 0x03);
DEFINE_SFR(__sfr_byte, __mp1h, 0x04);
DEFINE_SFR(__sfr_byte, __acc, 0x05);
DEFINE_SFR(__sfr_byte, __pcl, 0x06);
DEFINE_SFR(__sfr_byte, __tblp, 0x07);
DEFINE_SFR(__sfr_byte, __tblh, 0x08);
DEFINE_SFR(__sfr_byte, __tbhp, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__sfr_byte, __mp2l, 0x0d);
DEFINE_SFR(__sfr_byte, __mp2h, 0x0e);
DEFINE_SFR(__rstfc_type, __rstfc, 0x0f);
DEFINE_SFR(__integ_type, __integ, 0x10);
DEFINE_SFR(__intc0_type, __intc0, 0x11);
DEFINE_SFR(__intc1_type, __intc1, 0x12);
DEFINE_SFR(__intc2_type, __intc2, 0x13);
DEFINE_SFR(__pa_type, __pa, 0x14);
DEFINE_SFR(__pac_type, __pac, 0x15);
DEFINE_SFR(__papu_type, __papu, 0x16);
DEFINE_SFR(__pawu_type, __pawu, 0x17);
DEFINE_SFR(__lvdc_type, __lvdc, 0x18);
DEFINE_SFR(__scc_type, __scc, 0x19);
DEFINE_SFR(__wdtc_type, __wdtc, 0x1a);
DEFINE_SFR(__tb0c_type, __tb0c, 0x1b);
DEFINE_SFR(__hircc_type, __hircc, 0x1c);
DEFINE_SFR(__lvrc_type, __lvrc, 0x1d);
DEFINE_SFR(__eea_type, __eea, 0x1e);
DEFINE_SFR(__sfr_byte, __eed, 0x1f);
DEFINE_SFR(__sfr_byte, __sadol, 0x20);
DEFINE_SFR(__sfr_byte, __sadoh, 0x21);
DEFINE_SFR(__sadc0_type, __sadc0, 0x22);
DEFINE_SFR(__sadc1_type, __sadc1, 0x23);
DEFINE_SFR(__sadc2_type, __sadc2, 0x24);
DEFINE_SFR(__pb_type, __pb, 0x25);
DEFINE_SFR(__pbc_type, __pbc, 0x26);
DEFINE_SFR(__pbpu_type, __pbpu, 0x27);
DEFINE_SFR(__ctmc0_type, __ctmc0, 0x28);
DEFINE_SFR(__ctmc1_type, __ctmc1, 0x29);
DEFINE_SFR(__sfr_byte, __ctmdl, 0x2a);
DEFINE_SFR(__sfr_byte, __ctmdh, 0x2b);
DEFINE_SFR(__sfr_byte, __ctmal, 0x2c);
DEFINE_SFR(__sfr_byte, __ctmah, 0x2d);
DEFINE_SFR(__sfr_byte, __ctmrp, 0x2e);
DEFINE_SFR(__stmc0_type, __stmc0, 0x2f);
DEFINE_SFR(__stmc1_type, __stmc1, 0x30);
DEFINE_SFR(__sfr_byte, __stmdl, 0x31);
DEFINE_SFR(__sfr_byte, __stmdh, 0x32);
DEFINE_SFR(__sfr_byte, __stmal, 0x33);
DEFINE_SFR(__sfr_byte, __stmah, 0x34);
DEFINE_SFR(__stmrp_type, __stmrp, 0x35);
DEFINE_SFR(__hxtc_type, __hxtc, 0x36);
DEFINE_SFR(__ptmc0_type, __ptmc0, 0x37);
DEFINE_SFR(__ptmc1_type, __ptmc1, 0x38);
DEFINE_SFR(__sfr_byte, __ptmdl, 0x39);
DEFINE_SFR(__sfr_byte, __ptmdh, 0x3a);
DEFINE_SFR(__sfr_byte, __ptmal, 0x3b);
DEFINE_SFR(__sfr_byte, __ptmah, 0x3c);
DEFINE_SFR(__ptmrpl_type, __ptmrpl, 0x3d);
DEFINE_SFR(__ptmrph_type, __ptmrph, 0x3e);
DEFINE_SFR(__cmpc_type, __cmpc, 0x3f);
DEFINE_SFR(__pc_type, __pc, 0x41);
DEFINE_SFR(__pcc_type, __pcc, 0x42);
DEFINE_SFR(__pcpu_type, __pcpu, 0x43);
DEFINE_SFR(__lxtc_type, __lxtc, 0x44);
DEFINE_SFR(__simc0_type, __simc0, 0x45);
DEFINE_SFR(__simc1_type, __simc1, 0x46);
DEFINE_SFR(__sfr_byte, __simd, 0x47);
DEFINE_SFR(__sima_type, __sima, 0x48);
DEFINE_SFR(__simc2_type, __simc2, 0x48);
DEFINE_SFR(__simtoc_type, __simtoc, 0x49);
DEFINE_SFR(__vbgrc_type, __vbgrc, 0x4a);
DEFINE_SFR(__tb1c_type, __tb1c, 0x4b);
DEFINE_SFR(__mfi0_type, __mfi0, 0x4c);
DEFINE_SFR(__mfi1_type, __mfi1, 0x4d);
DEFINE_SFR(__mfi2_type, __mfi2, 0x4e);
DEFINE_SFR(__sledc0_type, __sledc0, 0x4f);
DEFINE_SFR(__sledc1_type, __sledc1, 0x50);
DEFINE_SFR(__ifs_type, __ifs, 0x51);
DEFINE_SFR(__pd_type, __pd, 0x52);
DEFINE_SFR(__pdc_type, __pdc, 0x53);
DEFINE_SFR(__pdpu_type, __pdpu, 0x54);
DEFINE_SFR(__usr_type, __usr, 0x55);
DEFINE_SFR(__ucr1_type, __ucr1, 0x56);
DEFINE_SFR(__ucr2_type, __ucr2, 0x57);
DEFINE_SFR(__brg_type, __brg, 0x58);
DEFINE_SFR(__txr_rxr_type, __txr_rxr, 0x59);
DEFINE_SFR(__lvpuc_type, __lvpuc, 0x5a);
DEFINE_SFR(__pas0_type, __pas0, 0x5b);
DEFINE_SFR(__pas1_type, __pas1, 0x5c);
DEFINE_SFR(__pbs0_type, __pbs0, 0x5d);
DEFINE_SFR(__pbs1_type, __pbs1, 0x5e);
DEFINE_SFR(__pcs0_type, __pcs0, 0x5f);
DEFINE_SFR(__pcs1_type, __pcs1, 0x60);
DEFINE_SFR(__pds0_type, __pds0, 0x61);
DEFINE_SFR(__slcdc0_type, __slcdc0, 0x62);
DEFINE_SFR(__slcds0_type, __slcds0, 0x63);
DEFINE_SFR(__slcds1_type, __slcds1, 0x64);
DEFINE_SFR(__slcds2_type, __slcds2, 0x65);
DEFINE_SFR(__psc0r_type, __psc0r, 0x66);
DEFINE_SFR(__psc1r_type, __psc1r, 0x67);
DEFINE_SFR(__rstc_type, __rstc, 0x68);
DEFINE_SFR(__fc0_type, __fc0, 0x69);
DEFINE_SFR(__sfr_byte, __fc1, 0x6a);
DEFINE_SFR(__fc2_type, __fc2, 0x6b);
DEFINE_SFR(__farl_type, __farl, 0x6c);
DEFINE_SFR(__farh_type, __farh, 0x6d);
DEFINE_SFR(__sfr_byte, __fd0l, 0x6e);
DEFINE_SFR(__sfr_byte, __fd0h, 0x6f);
DEFINE_SFR(__sfr_byte, __fd1l, 0x70);
DEFINE_SFR(__sfr_byte, __fd1h, 0x71);
DEFINE_SFR(__sfr_byte, __fd2l, 0x72);
DEFINE_SFR(__sfr_byte, __fd2h, 0x73);
DEFINE_SFR(__sfr_byte, __fd3l, 0x74);
DEFINE_SFR(__sfr_byte, __fd3h, 0x75);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);
DEFINE_SFR(__sfr_byte, __iar2, 0x0C);

#define _iar0     __iar0
#define _iar1     __iar1
#define _iar2     __iar2
#define _mp0      __mp0
#define _mp1l     __mp1l
#define _mp1h     __mp1h
#define _acc      __acc
#define _pcl      __pcl
#define _tblp     __tblp
#define _tblh     __tblh
#define _tbhp     __tbhp
#define _status   __status.byte
#define _mp2l     __mp2l
#define _mp2h     __mp2h
#define _rstfc    __rstfc.byte
#define _integ    __integ.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _papu     __papu.byte
#define _pawu     __pawu.byte
#define _lvdc     __lvdc.byte
#define _scc      __scc.byte
#define _wdtc     __wdtc.byte
#define _tb0c     __tb0c.byte
#define _hircc    __hircc.byte
#define _lvrc     __lvrc.byte
#define _eea      __eea.byte
#define _eed      __eed
#define _sadol    __sadol
#define _sadoh    __sadoh
#define _sadc0    __sadc0.byte
#define _sadc1    __sadc1.byte
#define _sadc2    __sadc2.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pbpu     __pbpu.byte
#define _ctmc0    __ctmc0.byte
#define _ctmc1    __ctmc1.byte
#define _ctmdl    __ctmdl
#define _ctmdh    __ctmdh
#define _ctmal    __ctmal
#define _ctmah    __ctmah
#define _ctmrp    __ctmrp
#define _stmc0    __stmc0.byte
#define _stmc1    __stmc1.byte
#define _stmdl    __stmdl
#define _stmdh    __stmdh
#define _stmal    __stmal
#define _stmah    __stmah
#define _stmrp    __stmrp.byte
#define _hxtc     __hxtc.byte
#define _ptmc0    __ptmc0.byte
#define _ptmc1    __ptmc1.byte
#define _ptmdl    __ptmdl
#define _ptmdh    __ptmdh
#define _ptmal    __ptmal
#define _ptmah    __ptmah
#define _ptmrpl   __ptmrpl.byte
#define _ptmrph   __ptmrph.byte
#define _cmpc     __cmpc.byte
#define _pc       __pc.byte
#define _pcc      __pcc.byte
#define _pcpu     __pcpu.byte
#define _lxtc     __lxtc.byte
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _simd     __simd
#define _sima     __sima.byte
#define _simc2    __simc2.byte
#define _simtoc   __simtoc.byte
#define _vbgrc    __vbgrc.byte
#define _tb1c     __tb1c.byte
#define _mfi0     __mfi0.byte
#define _mfi1     __mfi1.byte
#define _mfi2     __mfi2.byte
#define _sledc0   __sledc0.byte
#define _sledc1   __sledc1.byte
#define _ifs      __ifs.byte
#define _pd       __pd.byte
#define _pdc      __pdc.byte
#define _pdpu     __pdpu.byte
#define _usr      __usr.byte
#define _ucr1     __ucr1.byte
#define _ucr2     __ucr2.byte
#define _brg      __brg.byte
#define _txr_rxr  __txr_rxr.byte
#define _lvpuc    __lvpuc.byte
#define _pas0     __pas0.byte
#define _pas1     __pas1.byte
#define _pbs0     __pbs0.byte
#define _pbs1     __pbs1.byte
#define _pcs0     __pcs0.byte
#define _pcs1     __pcs1.byte
#define _pds0     __pds0.byte
#define _slcdc0   __slcdc0.byte
#define _slcds0   __slcds0.byte
#define _slcds1   __slcds1.byte
#define _slcds2   __slcds2.byte
#define _psc0r    __psc0r.byte
#define _psc1r    __psc1r.byte
#define _rstc     __rstc.byte
#define _fc0      __fc0.byte
#define _fc1      __fc1
#define _fc2      __fc2.byte
#define _farl     __farl.byte
#define _farh     __farh.byte
#define _fd0l     __fd0l
#define _fd0h     __fd0h
#define _fd1l     __fd1l
#define _fd1h     __fd1h
#define _fd2l     __fd2l
#define _fd2h     __fd2h
#define _fd3l     __fd3l
#define _fd3h     __fd3h
#define _eec      __eec.byte

#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _cz       __status.bits.__cz
#define _sc       __status.bits.__sc
#define _wrf      __rstfc.bits.__wrf
#define _lrf      __rstfc.bits.__lrf
#define _lvrf     __rstfc.bits.__lvrf
#define _rstf     __rstfc.bits.__rstf
#define _int0s0   __integ.bits.__int0s0
#define _int0s1   __integ.bits.__int0s1
#define _int1s0   __integ.bits.__int1s0
#define _int1s1   __integ.bits.__int1s1
#define _emi      __intc0.bits.__emi
#define _int0e    __intc0.bits.__int0e
#define _cpe      __intc0.bits.__cpe
#define _mf0e     __intc0.bits.__mf0e
#define _int0f    __intc0.bits.__int0f
#define _cpf      __intc0.bits.__cpf
#define _mf0f     __intc0.bits.__mf0f
#define _mf1e     __intc1.bits.__mf1e
#define _mf2e     __intc1.bits.__mf2e
#define _ade      __intc1.bits.__ade
#define _tb0e     __intc1.bits.__tb0e
#define _mf1f     __intc1.bits.__mf1f
#define _mf2f     __intc1.bits.__mf2f
#define _adf      __intc1.bits.__adf
#define _tb0f     __intc1.bits.__tb0f
#define _tb1e     __intc2.bits.__tb1e
#define _int1e    __intc2.bits.__int1e
#define _sime     __intc2.bits.__sime
#define _uarte    __intc2.bits.__uarte
#define _tb1f     __intc2.bits.__tb1f
#define _int1f    __intc2.bits.__int1f
#define _simf     __intc2.bits.__simf
#define _uartf    __intc2.bits.__uartf
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _fsiden   __scc.bits.__fsiden
#define _fhiden   __scc.bits.__fhiden
#define _fss      __scc.bits.__fss
#define _fhs      __scc.bits.__fhs
#define _cks0     __scc.bits.__cks0
#define _cks1     __scc.bits.__cks1
#define _cks2     __scc.bits.__cks2
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _tb00     __tb0c.bits.__tb00
#define _tb01     __tb0c.bits.__tb01
#define _tb02     __tb0c.bits.__tb02
#define _tb0on    __tb0c.bits.__tb0on
#define _hircen   __hircc.bits.__hircen
#define _hircf    __hircc.bits.__hircf
#define _hirc0    __hircc.bits.__hirc0
#define _hirc1    __hircc.bits.__hirc1
#define _lvs0     __lvrc.bits.__lvs0
#define _lvs1     __lvrc.bits.__lvs1
#define _lvs2     __lvrc.bits.__lvs2
#define _lvs3     __lvrc.bits.__lvs3
#define _lvs4     __lvrc.bits.__lvs4
#define _lvs5     __lvrc.bits.__lvs5
#define _lvs6     __lvrc.bits.__lvs6
#define _lvs7     __lvrc.bits.__lvs7
#define _eea0     __eea.bits.__eea0
#define _eea1     __eea.bits.__eea1
#define _eea2     __eea.bits.__eea2
#define _eea3     __eea.bits.__eea3
#define _eea4     __eea.bits.__eea4
#define _eea5     __eea.bits.__eea5
#define _eea6     __eea.bits.__eea6
#define _sacs0    __sadc0.bits.__sacs0
#define _sacs1    __sadc0.bits.__sacs1
#define _sacs2    __sadc0.bits.__sacs2
#define _sacs3    __sadc0.bits.__sacs3
#define _adrfs    __sadc0.bits.__adrfs
#define _adcen    __sadc0.bits.__adcen
#define _adbz     __sadc0.bits.__adbz
#define _start    __sadc0.bits.__start
#define _sacks0   __sadc1.bits.__sacks0
#define _sacks1   __sadc1.bits.__sacks1
#define _sacks2   __sadc1.bits.__sacks2
#define _sains0   __sadc1.bits.__sains0
#define _sains1   __sadc1.bits.__sains1
#define _sains2   __sadc1.bits.__sains2
#define _sains3   __sadc1.bits.__sains3
#define _pgags0   __sadc2.bits.__pgags0
#define _pgags1   __sadc2.bits.__pgags1
#define _savrs0   __sadc2.bits.__savrs0
#define _savrs1   __sadc2.bits.__savrs1
#define _pgais    __sadc2.bits.__pgais
#define _adpgaen  __sadc2.bits.__adpgaen
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pb3      __pb.bits.__pb3
#define _pb4      __pb.bits.__pb4
#define _pb5      __pb.bits.__pb5
#define _pb6      __pb.bits.__pb6
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbc3     __pbc.bits.__pbc3
#define _pbc4     __pbc.bits.__pbc4
#define _pbc5     __pbc.bits.__pbc5
#define _pbc6     __pbc.bits.__pbc6
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _pbpu3    __pbpu.bits.__pbpu3
#define _pbpu4    __pbpu.bits.__pbpu4
#define _pbpu5    __pbpu.bits.__pbpu5
#define _pbpu6    __pbpu.bits.__pbpu6
#define _cton     __ctmc0.bits.__cton
#define _ctck0    __ctmc0.bits.__ctck0
#define _ctck1    __ctmc0.bits.__ctck1
#define _ctck2    __ctmc0.bits.__ctck2
#define _ctpau    __ctmc0.bits.__ctpau
#define _ctcclr   __ctmc1.bits.__ctcclr
#define _ctdpx    __ctmc1.bits.__ctdpx
#define _ctpol    __ctmc1.bits.__ctpol
#define _ctoc     __ctmc1.bits.__ctoc
#define _ctio0    __ctmc1.bits.__ctio0
#define _ctio1    __ctmc1.bits.__ctio1
#define _ctm0     __ctmc1.bits.__ctm0
#define _ctm1     __ctmc1.bits.__ctm1
#define _ston     __stmc0.bits.__ston
#define _stck0    __stmc0.bits.__stck0
#define _stck1    __stmc0.bits.__stck1
#define _stck2    __stmc0.bits.__stck2
#define _stpau    __stmc0.bits.__stpau
#define _stcclr   __stmc1.bits.__stcclr
#define _stdpx    __stmc1.bits.__stdpx
#define _stpol    __stmc1.bits.__stpol
#define _stoc     __stmc1.bits.__stoc
#define _stio0    __stmc1.bits.__stio0
#define _stio1    __stmc1.bits.__stio1
#define _stm0     __stmc1.bits.__stm0
#define _stm1     __stmc1.bits.__stm1
#define _strp0    __stmrp.bits.__strp0
#define _strp1    __stmrp.bits.__strp1
#define _strp2    __stmrp.bits.__strp2
#define _strp3    __stmrp.bits.__strp3
#define _strp4    __stmrp.bits.__strp4
#define _strp5    __stmrp.bits.__strp5
#define _strp6    __stmrp.bits.__strp6
#define _strp7    __stmrp.bits.__strp7
#define _hxten    __hxtc.bits.__hxten
#define _hxtf     __hxtc.bits.__hxtf
#define _hxtm     __hxtc.bits.__hxtm
#define _pton     __ptmc0.bits.__pton
#define _ptck0    __ptmc0.bits.__ptck0
#define _ptck1    __ptmc0.bits.__ptck1
#define _ptck2    __ptmc0.bits.__ptck2
#define _ptpau    __ptmc0.bits.__ptpau
#define _ptcclr   __ptmc1.bits.__ptcclr
#define _ptcapts  __ptmc1.bits.__ptcapts
#define _ptpol    __ptmc1.bits.__ptpol
#define _ptoc     __ptmc1.bits.__ptoc
#define _ptio0    __ptmc1.bits.__ptio0
#define _ptio1    __ptmc1.bits.__ptio1
#define _ptm0     __ptmc1.bits.__ptm0
#define _ptm1     __ptmc1.bits.__ptm1
#define _ptrp0    __ptmrpl.bits.__ptrp0
#define _ptrp1    __ptmrpl.bits.__ptrp1
#define _ptrp2    __ptmrpl.bits.__ptrp2
#define _ptrp3    __ptmrpl.bits.__ptrp3
#define _ptrp4    __ptmrpl.bits.__ptrp4
#define _ptrp5    __ptmrpl.bits.__ptrp5
#define _ptrp6    __ptmrpl.bits.__ptrp6
#define _ptrp7    __ptmrpl.bits.__ptrp7
#define _ptrp8    __ptmrph.bits.__ptrp8
#define _ptrp9    __ptmrph.bits.__ptrp9
#define _cmphyen  __cmpc.bits.__cmphyen
#define _cmpo     __cmpc.bits.__cmpo
#define _cmppol   __cmpc.bits.__cmppol
#define _cmpen    __cmpc.bits.__cmpen
#define _pc0      __pc.bits.__pc0
#define _pc1      __pc.bits.__pc1
#define _pc2      __pc.bits.__pc2
#define _pc3      __pc.bits.__pc3
#define _pc4      __pc.bits.__pc4
#define _pc5      __pc.bits.__pc5
#define _pc6      __pc.bits.__pc6
#define _pcc0     __pcc.bits.__pcc0
#define _pcc1     __pcc.bits.__pcc1
#define _pcc2     __pcc.bits.__pcc2
#define _pcc3     __pcc.bits.__pcc3
#define _pcc4     __pcc.bits.__pcc4
#define _pcc5     __pcc.bits.__pcc5
#define _pcc6     __pcc.bits.__pcc6
#define _pcpu0    __pcpu.bits.__pcpu0
#define _pcpu1    __pcpu.bits.__pcpu1
#define _pcpu2    __pcpu.bits.__pcpu2
#define _pcpu3    __pcpu.bits.__pcpu3
#define _pcpu4    __pcpu.bits.__pcpu4
#define _pcpu5    __pcpu.bits.__pcpu5
#define _pcpu6    __pcpu.bits.__pcpu6
#define _lxten    __lxtc.bits.__lxten
#define _lxtf     __lxtc.bits.__lxtf
#define _lxtsp    __lxtc.bits.__lxtsp
#define _simicf   __simc0.bits.__simicf
#define _simen    __simc0.bits.__simen
#define _simdeb0  __simc0.bits.__simdeb0
#define _simdeb1  __simc0.bits.__simdeb1
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _iamwu    __simc1.bits.__iamwu
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _sima0    __sima.bits.__sima0
#define _sima1    __sima.bits.__sima1
#define _sima2    __sima.bits.__sima2
#define _sima3    __sima.bits.__sima3
#define _sima4    __sima.bits.__sima4
#define _sima5    __sima.bits.__sima5
#define _sima6    __sima.bits.__sima6
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _simtos0  __simtoc.bits.__simtos0
#define _simtos1  __simtoc.bits.__simtos1
#define _simtos2  __simtoc.bits.__simtos2
#define _simtos3  __simtoc.bits.__simtos3
#define _simtos4  __simtoc.bits.__simtos4
#define _simtos5  __simtoc.bits.__simtos5
#define _simtof   __simtoc.bits.__simtof
#define _simtoen  __simtoc.bits.__simtoen
#define _vbgren   __vbgrc.bits.__vbgren
#define _tb10     __tb1c.bits.__tb10
#define _tb11     __tb1c.bits.__tb11
#define _tb12     __tb1c.bits.__tb12
#define _tb1on    __tb1c.bits.__tb1on
#define _stmpe    __mfi0.bits.__stmpe
#define _stmae    __mfi0.bits.__stmae
#define _stmpf    __mfi0.bits.__stmpf
#define _stmaf    __mfi0.bits.__stmaf
#define _ptmpe    __mfi1.bits.__ptmpe
#define _ptmae    __mfi1.bits.__ptmae
#define _ctmpe    __mfi1.bits.__ctmpe
#define _ctmae    __mfi1.bits.__ctmae
#define _ptmpf    __mfi1.bits.__ptmpf
#define _ptmaf    __mfi1.bits.__ptmaf
#define _ctmpf    __mfi1.bits.__ctmpf
#define _ctmaf    __mfi1.bits.__ctmaf
#define _lve      __mfi2.bits.__lve
#define _dee      __mfi2.bits.__dee
#define _lvf      __mfi2.bits.__lvf
#define _def      __mfi2.bits.__def
#define _sledc00  __sledc0.bits.__sledc00
#define _sledc01  __sledc0.bits.__sledc01
#define _sledc02  __sledc0.bits.__sledc02
#define _sledc03  __sledc0.bits.__sledc03
#define _sledc04  __sledc0.bits.__sledc04
#define _sledc05  __sledc0.bits.__sledc05
#define _sledc06  __sledc0.bits.__sledc06
#define _sledc07  __sledc0.bits.__sledc07
#define _sledc10  __sledc1.bits.__sledc10
#define _sledc11  __sledc1.bits.__sledc11
#define _sledc12  __sledc1.bits.__sledc12
#define _sledc13  __sledc1.bits.__sledc13
#define _sledc14  __sledc1.bits.__sledc14
#define _sledc15  __sledc1.bits.__sledc15
#define _rxps     __ifs.bits.__rxps
#define _scsbps   __ifs.bits.__scsbps
#define _sck_sclps __ifs.bits.__sck_sclps
#define _sdi_sdaps __ifs.bits.__sdi_sdaps
#define _int0ps   __ifs.bits.__int0ps
#define _int1ps   __ifs.bits.__int1ps
#define _pd0      __pd.bits.__pd0
#define _pd1      __pd.bits.__pd1
#define _pd2      __pd.bits.__pd2
#define _pd3      __pd.bits.__pd3
#define _pdc0     __pdc.bits.__pdc0
#define _pdc1     __pdc.bits.__pdc1
#define _pdc2     __pdc.bits.__pdc2
#define _pdc3     __pdc.bits.__pdc3
#define _pdpu0    __pdpu.bits.__pdpu0
#define _pdpu1    __pdpu.bits.__pdpu1
#define _pdpu2    __pdpu.bits.__pdpu2
#define _pdpu3    __pdpu.bits.__pdpu3
#define _txif     __usr.bits.__txif
#define _tidle    __usr.bits.__tidle
#define _rxif     __usr.bits.__rxif
#define _ridle    __usr.bits.__ridle
#define _oerr     __usr.bits.__oerr
#define _ferr     __usr.bits.__ferr
#define _nf       __usr.bits.__nf
#define _perr     __usr.bits.__perr
#define _tx8      __ucr1.bits.__tx8
#define _rx8      __ucr1.bits.__rx8
#define _txbrk    __ucr1.bits.__txbrk
#define _stops    __ucr1.bits.__stops
#define _prt      __ucr1.bits.__prt
#define _pren     __ucr1.bits.__pren
#define _bno      __ucr1.bits.__bno
#define _uarten   __ucr1.bits.__uarten
#define _teie     __ucr2.bits.__teie
#define _tiie     __ucr2.bits.__tiie
#define _rie      __ucr2.bits.__rie
#define _wake     __ucr2.bits.__wake
#define _adden    __ucr2.bits.__adden
#define _brgh     __ucr2.bits.__brgh
#define _rxen     __ucr2.bits.__rxen
#define _txen     __ucr2.bits.__txen
#define _brg0     __brg.bits.__brg0
#define _brg1     __brg.bits.__brg1
#define _brg2     __brg.bits.__brg2
#define _brg3     __brg.bits.__brg3
#define _brg4     __brg.bits.__brg4
#define _brg5     __brg.bits.__brg5
#define _brg6     __brg.bits.__brg6
#define _brg7     __brg.bits.__brg7
#define _txrx0    __txr_rxr.bits.__txrx0
#define _txrx1    __txr_rxr.bits.__txrx1
#define _txrx2    __txr_rxr.bits.__txrx2
#define _txrx3    __txr_rxr.bits.__txrx3
#define _txrx4    __txr_rxr.bits.__txrx4
#define _txrx5    __txr_rxr.bits.__txrx5
#define _txrx6    __txr_rxr.bits.__txrx6
#define _txrx7    __txr_rxr.bits.__txrx7
#define _lvpu     __lvpuc.bits.__lvpu
#define _pas00    __pas0.bits.__pas00
#define _pas01    __pas0.bits.__pas01
#define _pas02    __pas0.bits.__pas02
#define _pas03    __pas0.bits.__pas03
#define _pas04    __pas0.bits.__pas04
#define _pas05    __pas0.bits.__pas05
#define _pas06    __pas0.bits.__pas06
#define _pas07    __pas0.bits.__pas07
#define _pas10    __pas1.bits.__pas10
#define _pas11    __pas1.bits.__pas11
#define _pas12    __pas1.bits.__pas12
#define _pas13    __pas1.bits.__pas13
#define _pas14    __pas1.bits.__pas14
#define _pas15    __pas1.bits.__pas15
#define _pas16    __pas1.bits.__pas16
#define _pas17    __pas1.bits.__pas17
#define _pbs00    __pbs0.bits.__pbs00
#define _pbs01    __pbs0.bits.__pbs01
#define _pbs02    __pbs0.bits.__pbs02
#define _pbs03    __pbs0.bits.__pbs03
#define _pbs04    __pbs0.bits.__pbs04
#define _pbs05    __pbs0.bits.__pbs05
#define _pbs06    __pbs0.bits.__pbs06
#define _pbs07    __pbs0.bits.__pbs07
#define _pbs10    __pbs1.bits.__pbs10
#define _pbs11    __pbs1.bits.__pbs11
#define _pbs12    __pbs1.bits.__pbs12
#define _pbs13    __pbs1.bits.__pbs13
#define _pbs14    __pbs1.bits.__pbs14
#define _pbs15    __pbs1.bits.__pbs15
#define _pcs00    __pcs0.bits.__pcs00
#define _pcs01    __pcs0.bits.__pcs01
#define _pcs02    __pcs0.bits.__pcs02
#define _pcs03    __pcs0.bits.__pcs03
#define _pcs04    __pcs0.bits.__pcs04
#define _pcs05    __pcs0.bits.__pcs05
#define _pcs06    __pcs0.bits.__pcs06
#define _pcs07    __pcs0.bits.__pcs07
#define _pcs10    __pcs1.bits.__pcs10
#define _pcs11    __pcs1.bits.__pcs11
#define _pcs12    __pcs1.bits.__pcs12
#define _pcs13    __pcs1.bits.__pcs13
#define _pcs14    __pcs1.bits.__pcs14
#define _pcs15    __pcs1.bits.__pcs15
#define _pds00    __pds0.bits.__pds00
#define _pds01    __pds0.bits.__pds01
#define _pds02    __pds0.bits.__pds02
#define _pds03    __pds0.bits.__pds03
#define _pds04    __pds0.bits.__pds04
#define _pds05    __pds0.bits.__pds05
#define _pds06    __pds0.bits.__pds06
#define _pds07    __pds0.bits.__pds07
#define _lcden    __slcdc0.bits.__lcden
#define _isel0    __slcdc0.bits.__isel0
#define _isel1    __slcdc0.bits.__isel1
#define _frame    __slcdc0.bits.__frame
#define _comsegs0 __slcds0.bits.__comsegs0
#define _comsegs1 __slcds0.bits.__comsegs1
#define _comsegs2 __slcds0.bits.__comsegs2
#define _comsegs3 __slcds0.bits.__comsegs3
#define _comsegs4 __slcds0.bits.__comsegs4
#define _comsegs5 __slcds0.bits.__comsegs5
#define _comsegs6 __slcds0.bits.__comsegs6
#define _comsegs7 __slcds0.bits.__comsegs7
#define _comsegs8 __slcds1.bits.__comsegs8
#define _comsegs9 __slcds1.bits.__comsegs9
#define _comsegs10 __slcds1.bits.__comsegs10
#define _comsegs11 __slcds1.bits.__comsegs11
#define _comsegs12 __slcds1.bits.__comsegs12
#define _comsegs13 __slcds1.bits.__comsegs13
#define _comsegs14 __slcds1.bits.__comsegs14
#define _comsegs15 __slcds1.bits.__comsegs15
#define _comsegs16 __slcds2.bits.__comsegs16
#define _comsegs17 __slcds2.bits.__comsegs17
#define _comsegs18 __slcds2.bits.__comsegs18
#define _comsegs19 __slcds2.bits.__comsegs19
#define _comsegs20 __slcds2.bits.__comsegs20
#define _comsegs21 __slcds2.bits.__comsegs21
#define _clksel00 __psc0r.bits.__clksel00
#define _clksel01 __psc0r.bits.__clksel01
#define _clksel10 __psc1r.bits.__clksel10
#define _clksel11 __psc1r.bits.__clksel11
#define _rstc0    __rstc.bits.__rstc0
#define _rstc1    __rstc.bits.__rstc1
#define _rstc2    __rstc.bits.__rstc2
#define _rstc3    __rstc.bits.__rstc3
#define _rstc4    __rstc.bits.__rstc4
#define _rstc5    __rstc.bits.__rstc5
#define _rstc6    __rstc.bits.__rstc6
#define _rstc7    __rstc.bits.__rstc7
#define _frd      __fc0.bits.__frd
#define _frden    __fc0.bits.__frden
#define _fwt      __fc0.bits.__fwt
#define _fwpen    __fc0.bits.__fwpen
#define _fmod0    __fc0.bits.__fmod0
#define _fmod1    __fc0.bits.__fmod1
#define _fmod2    __fc0.bits.__fmod2
#define _cfwen    __fc0.bits.__cfwen
#define _clwb     __fc2.bits.__clwb
#define _fwerts   __fc2.bits.__fwerts
#define _fa0      __farl.bits.__fa0
#define _fa1      __farl.bits.__fa1
#define _fa2      __farl.bits.__fa2
#define _fa3      __farl.bits.__fa3
#define _fa4      __farl.bits.__fa4
#define _fa5      __farl.bits.__fa5
#define _fa6      __farl.bits.__fa6
#define _fa7      __farl.bits.__fa7
#define _fa8      __farh.bits.__fa8
#define _fa9      __farh.bits.__fa9
#define _fa10     __farh.bits.__fa10
#define _fa11     __farh.bits.__fa11
#define _fa12     __farh.bits.__fa12
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren
#define _mode     __eec.bits.__mode
#define _er       __eec.bits.__er
#define _eren     __eec.bits.__eren
#define _ewerts   __eec.bits.__ewerts

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _HT66F3195_H_
